updating to match Mosaic project structure, also some doc tweaks

diff --git a/developer/tool🖉/release b/developer/tool🖉/release
--- a/developer/tool🖉/release
+++ b/developer/tool🖉/release
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 script_afp=$(realpath "${BASH_SOURCE[0]}")
 
+# before running this script, gather everything needed for the release on the scratchpad
+
 # input guards
 
   if [ -z "$REPO_HOME" ]; then
@@ -10,23 +12,24 @@ script_afp=$(realpath "${BASH_SOURCE[0]}")
 
   env_must_be="developer/tool🖉/env"
   if [ "$ENV" != "$env_must_be" ]; then
-    echo "$(script_fp):: error: must be run in the $env_must_be environment"
+    echo "$(script_fp):: must be run in the $env_must_be environment"
     exit 1
   fi
 
-# script local environment
+  cd "$REPO_HOME"/developer
 
-  release_dir="$REPO_HOME/release"
-  bash_dir="$REPO_HOME/developer/bash"
-  project_jar_fp="$REPO_HOME/developer/jvm/"$PROJECT".jar"
-  wrapper=$(bash_wrapper_list)
-
-
-  if [ ! -d "$release_dir" ]; then
-    mkdir -p "$release_dir"
+  if [ ! -d scratchpad ]; then
+    echo "$(script_fp):: no scratchpad directory"
+    exit 1
   fi
 
-  # Function to copy and set permissions
+
+# Inform the user
+
+  echo "The pwd for this script is `pwd`."
+
+# Function to copy and set permissions
+
   install_file() {
     source_fp="$1"
     target_dp="$2"
@@ -46,17 +49,33 @@ script_afp=$(realpath "${BASH_SOURCE[0]}")
       echo "Installed $(basename "$source_fp") to $target_dp with permissions $perms"
     fi
   }
- 
-# do the release
 
-  echo "Starting release process..."
+# scratchpad --> .jar file 
 
-  # Install the JAR file
-  install_file "$project_jar_fp" "$release_dir" "ug+r"
+  mkdir -p jvm
+  jar_file=$(realpath jvm/"$PROJECT".jar)
 
-  # Install bash wrappers
+  pushd scratchpad
+
+  echo "scratchpad -> $jar_file"
+  jar cf $jar_file *
+  if [ $? -ne 0 ]; then
+    echo "Failed to create $jar_file file."
+    exit 1
+  fi
+
+  popd
+
+# move files to the release dir
+
+  release_dir="$REPO_HOME/release"
+  bash_dir="$REPO_HOME/developer/bash"
+  wrapper=$(bash_wrapper_list)
+
+  install_file "$jar_file" "$release_dir" "ug+r"
+
   for wrapper in $wrapper; do
-    install_file "$bash_dir/$wrapper" "$release_dir" "ug+r+x"
+    install_file "$bash_dir"/"$wrapper" "$release_dir" "ug+r+x"
   done
 
 echo "$(script_fp) done."
diff --git a/tester/tool🖉/make b/tester/tool🖉/make
--- a/tester/tool🖉/make
+++ b/tester/tool🖉/make
@@ -1,32 +1,52 @@
 #!/bin/env bash
+set -x
 script_afp=$(realpath "${BASH_SOURCE[0]}")
 
 # input guards
 
-  env_must_be="tester/tool🖉/env"
-  if [ "$ENV" != "$env_must_be" ]; then
-    echo "$(script_fp):: error: must be run in the $env_must_be environment"
-    exit 1
-  fi
+env_must_be="tester/tool🖉/env"
+if [ "$ENV" != "$env_must_be" ]; then
+  echo "$(script_fp):: error: must be run in the $env_must_be environment"
+  exit 1
+fi
 
 echo "Compiling files..."
 
-  set -x
-  cd $REPO_HOME/tester
-  javac -g -d scratchpad javac🖉/*.java
-  jar cf jvm/Test_"$PROJECT".jar -C scratchpad .
-  set +x 
+set -x
+cd $REPO_HOME/tester
 
-echo "Creating bash wrappers..."
-  mkdir -p bash
-  # wrapper is a space separated list
-  wrapper=$(bash_wrapper_list)
-  for file in $wrapper;do
-    cat > bash/$file << EOL
+# Get the list of tests to compile
+# wrapper is a space-separated list
+list=$(list)
+
+# make class files
+for file in $list; do
+  javac -g -d scratchpad "javac🖉/$file.java"
+done
+set +x 
+
+echo "Making jvm scripts ..."
+mkdir -p jvm
+for file in $list; do
+  cat > jvm/$file << EOL
 #!/bin/env bash
 java $file
 EOL
-    chmod +x bash/$file
+  chmod +x jvm/$file
+  done
+
+echo "Making jdwp debug server scripts..."
+mkdir -p jdwp_server
+for file in $list; do
+  cat > jdwp_server/$file << EOL
+#!/bin/env bash
+java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 $file
+EOL
+  chmod +x jdwp_server/$file
   done
 
 echo "$(script_fp) done."
+
+
+
+set +x
