rearranging for block testing

diff --git a/developer/tool/clean_release b/developer/tool/clean_release
--- a/developer/tool/clean_release
+++ b/developer/tool/clean_release
@@ -1,31 +1,28 @@
 #!/bin/bash
-# remove file made by `make` and by `release`
+# remove files made by `make` and by `release`
 
-script_name=$(basename ${BASH_SOURCE[0]})
-error=false
-if [ -z "$REPO_HOME" ]; then
-  echo "$script_name:: REPO_HOME is not set."
-  error=true
-fi
-if [ -z "$ENV_DEVELOPER_LOCAL" ]; then
-  echo "$script_name:: ENV_DEV_BUILD is not set."
-  error=true
-fi
-if [ error ]; then
-  exit 1
-fi
+# input guards
 
-# Define release directory
-release_dir="$REPO_HOME"/release_candidate
-wrapper=build
+  env_must_be="developer/tool/env"
+  if [ "$ENV" != "$env_must_be" ]; then
+    echo "$(script_fp):: error: must be run in the $env_must_be environment"
+    exit 1
+  fi
 
-set -x
-cd "$REPO_HOME"/developer
-rm -rf scratch_pad/*
-rm -f jvm/Ariadne.jar
-rm -f shell/"$wrapper"
-rm -f "$release_dir"/Ariadne.jar
-rm -f "$release_dir"/{$wrapper}
-set +x
+# things to clean
 
-echo "$script_name done."
+  release_dir="$REPO_HOME"/release
+  wrapper=build
+
+# remove files
+  set -x
+  cd "$REPO_HOME"/developer
+  rm -r scratch_pad/com/ReasoningTechnology/Ariadne
+  rm jvm/Ariadne.jar
+  rm shell/{$wrapper}
+  rm -f "$release_dir"/Ariadne.jar
+  rm -f "$release_dir"/{$wrapper}
+  set +x
+
+echo "$(script_fn) done."
+
diff --git a/developer/tool/env b/developer/tool/env
--- a/developer/tool/env
+++ b/developer/tool/env
@@ -1,32 +1,27 @@
 #!/usr/bin/env bash
 
-## input guards
+# input guards
 
-# instead of bailing, we will go fetch what we need
-env_should_be="tool_shared/bespoke/env"
-if [ "$ENV" != "$env_should_be" ]; then
-  source "$REPO_HOME"/"$env_should_be"
-fi
+  env_must_be="tool_shared/bespoke/env"
+  if [ "$ENV" != "$env_must_be" ]; then
+    echo "$(script_fp):: error: must be run in the $env_must_be environment"
+    exit 1
+  fi
 
-if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
-  echo "$script_name:: This script must be sourced, not executed."
-  exit 1
-fi
+  if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
+    echo "$script_name:: This script must be sourced, not executed."
+    exit 1
+  fi
 
-## so we can do the build
-
-cd "$REPO_HOME"/developer/
-
-export ENV=$(script_fp)
-export PROJECT="$PROJECT"_developer
+# so we can do the build
 
 export PATH=\
 "$REPO_HOME"/developer/tool/\
 :"$REPO_HOME"/tool_shared/bespoke/\
-"$JAVA_HOME"/bin\
+:"$JAVA_HOME"/bin\
 :"$PATH"
 
-## so we can run locally the stuff we built,
+# so we can run the stuff we built locally.
 
 export CLASSPATH=\
 "$REPO_HOME"/developer/jvm\
@@ -38,13 +33,17 @@ export PATH=\
 "$REPO_HOME"/developer/shell\
 :"$PATH"
 
-## misc
+# misc
 
-# make .githolder and .gitignore visible
-alias ls="ls -a"
+  # make .githolder and .gitignore visible
+  alias ls="ls -a"
 
-echo "$ENV complete."
+# some feedback to show all went well
 
+  export PROJECT="$PROJECT"_developer
+  export ENV=$(script_fp)
+  echo ENV "$ENV"
+  cd "$REPO_HOME"/developer/
 
 
 
diff --git a/developer/tool/make b/developer/tool/make
--- a/developer/tool/make
+++ b/developer/tool/make
@@ -1,48 +1,49 @@
 #!/bin/env bash
 
-script_name=$(basename ${BASH_SOURCE[0]})
-if [ -z "$ENV_DEVELOPER_LOCAL" ]; then
-  echo "$script_name:: script can only be run from the developer environment"
-  return 1
-fi
+# input guards
 
-# work from the developer directory
-cd "$REPO_HOME"/developer
+  env_must_be="developer/tool/env"
+  if [ "$ENV" != "$env_must_be" ]; then
+    echo "$(script_fp):: error: must be run in the $env_must_be environment"
+    exit 1
+  fi
+
+  cd "$REPO_HOME"/developer
 
 echo "Compiling files..."
-javac -d scratch_pad javac/*.java
-
-if [ $? -ne 0 ]; then
-  echo "Compilation failed."
-  exit 1
-fi
+  set -x
+  javac -d scratch_pad javac/*.java
+  set +x
+  if [ $? -ne 0 ]; then
+    echo "Compilation failed."
+    exit 1
+  fi
 
 echo "Creating JAR file..."
-jar_file=jvm/Ariadne.jar
-mkdir -p jvm
-jar cf $jar_file -C scratch_pad .
+  set -x
+  jar_file=jvm/Ariadne.jar
+  mkdir -p jvm
+  jar cf $jar_file -C scratch_pad .
+  set +x
+  if [ $? -eq 0 ]; then
+    echo "JAR file created successfully: $jar_file"
+  else
+    echo "Failed to create JAR file."
+    exit 1
+  fi
 
-if [ $? -eq 0 ]; then
-  echo "JAR file created successfully: $jar_file"
-else
-  echo "Failed to create JAR file."
-  exit 1
-fi
-
-# for these to run, the jar file must be in the CLASSPATH
 echo "Creating shell wrappers..."
-mkdir -p shell
+  mkdir -p shell
+  wrapper=build
+  for file in $wrapper;do
 
-wrapper=build
-for file in $wrapper;do
-
-cat > shell/$file << EOL
+  cat > shell/$file << EOL
 #!/bin/bash
 java com/ReasoningTechnology/Ariadne/$file
 EOL
-chmod +x shell/$file
+    chmod +x shell/$file
 
 done
 
-echo "$script_name done."
+echo "$(script_fp) done."
 
diff --git a/developer/tool/release b/developer/tool/release
--- a/developer/tool/release
+++ b/developer/tool/release
@@ -1,56 +1,61 @@
 #!/bin/bash
 
-script_name=$(basename ${BASH_SOURCE[0]})
-if [ -z "$REPO_HOME" ]; then
-  echo "$script_name:: REPO_HOME is not set."
-  exit 1
-fi
+# input guards
 
-if [ -z "$ENV_LOCAL_DEVELOPER" ]; then
-  echo "$script_name:: ENV_DEV_BUILD is not set."
-  exit 1
-fi
-
-release_dir="$REPO_HOME/release"
-shell_dir="$REPO_HOME/developer/shell"
-Ariadne_jar_fp="$REPO_HOME/developer/jvm/Ariadne.jar"
-wrapper=build
-
-
-
-if [ ! -d "$release_dir" ]; then
-  mkdir -p "$release_dir"
-fi
-
-# Function to copy and set permissions
-install_file() {
-  source_fp="$1"
-  target_dp="$2"
-  perms="$3"
-  
-  target_file="$target_dp/$(basename "$source_fp")"
-
-  if [ ! -f "$source_fp" ]; then
-    echo "install_file:: Source file '$source_fp' does not exist."
-    return 1
-  fi
-
-  if ! install -m "$perms" "$source_fp" "$target_file"; then
-    echo "Error: Failed to install $(basename "$source_fp") to $target_dp"
+  if [ -z "$REPO_HOME" ]; then
+    echo "$(script_fp):: REPO_HOME is not set."
     exit 1
-  else
-    echo "Installed $(basename "$source_fp") to $target_dp with permissions $perms"
   fi
-}
+
+  env_must_be="developer/tool/env"
+  if [ "$ENV" != "$env_must_be" ]; then
+    echo "$(script_fp):: error: must be run in the $env_must_be environment"
+    exit 1
+  fi
+
+# script local environment
+
+  release_dir="$REPO_HOME/release"
+  shell_dir="$REPO_HOME/developer/shell"
+  Ariadne_jar_fp="$REPO_HOME/developer/jvm/Ariadne.jar"
+  wrapper=build
+
+
+  if [ ! -d "$release_dir" ]; then
+    mkdir -p "$release_dir"
+  fi
+
+  # Function to copy and set permissions
+  install_file() {
+    source_fp="$1"
+    target_dp="$2"
+    perms="$3"
+
+    target_file="$target_dp/$(basename "$source_fp")"
+
+    if [ ! -f "$source_fp" ]; then
+      echo "install_file:: Source file '$source_fp' does not exist."
+      return 1
+    fi
+
+    if ! install -m "$perms" "$source_fp" "$target_file"; then
+      echo "Error: Failed to install $(basename "$source_fp") to $target_dp"
+      exit 1
+    else
+      echo "Installed $(basename "$source_fp") to $target_dp with permissions $perms"
+    fi
+  }
  
-echo "Starting release process..."
+# do the release
 
-# Install the JAR file
-install_file "$Ariadne_jar_fp" "$release_dir" "ug+r"
+  echo "Starting release process..."
 
-# Install shell wrappers
-for wrapper in $wrapper; do
-  install_file "$shell_dir/$wrapper" "$release_dir" "ug+r+x"
-done
+  # Install the JAR file
+  install_file "$Ariadne_jar_fp" "$release_dir" "ug+r"
 
-echo "$script_name done."
+  # Install shell wrappers
+  for wrapper in $wrapper; do
+    install_file "$shell_dir/$wrapper" "$release_dir" "ug+r+x"
+  done
+
+echo "$(script_fp) done."
diff --git a/tester/tool/env b/tester/tool/env
--- a/tester/tool/env
+++ b/tester/tool/env
@@ -1,32 +1,41 @@
 #!/usr/bin/env bash
 
-## input guards
+# input guards
 
-# instead of bailing, we will go fetch what we need
-env_should_be="tool_shared/bespoke/env"
-if [ "$ENV" != "$env_should_be" ]; then
-  source "$REPO_HOME"/"$env_should_be"
-fi
+  env_must_be="tool_shared/bespoke/env"
+  if [ "$ENV" != "$env_must_be" ]; then
+    echo "$(script_fp):: error: must be run in the $env_must_be environment"
+    exit 1
+  fi
 
-if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
-  echo "$script_name:: This script must be sourced, not executed."
-  exit 1
-fi
+  if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
+    echo "$script_name:: This script must be sourced, not executed."
+    exit 1
+  fi
 
-cd "$REPO_HOME"/tester/
-
-export ENV=$(script_fp)
-export PROJECT="$PROJECT"_tester
+# so we can do testing
 
 export PATH=\
 "$REPO_HOME"/tester/tool/\
 :"$REPO_HOME"/tool_shared/bespoke/\
-"$JAVA_HOME"/bin\
+:"$JAVA_HOME"/bin\
 :"$PATH"
 
 export CLASSPATH=\
-:"$REPO_HOME"/developer/release/Ariadne.jar\
-:"$JAVA_HOME"/lib\
+"$JAVA_HOME"/lib\
+:"$REPO_HOME"/release/Ariadne.jar\
+:"$REPO_HOME"/tester/jvm/TestBench.jar\
+:"$REPO_HOME"/tester/jvm/AriadneTestBench.jar\
 :"$CLASSPATH"
 
-echo "$ENV complete."
+# misc
+
+  # make .githolder and .gitignore visible
+  alias ls="ls -a"
+
+# some feedback to show all went well
+
+  export PROJECT="$PROJECT"_tester
+  export ENV=$(script_fp)
+  echo ENV "$ENV"
+  cd "$REPO_HOME"/tester/
